apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jamph-rag-api-umami
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8004
  accessPolicy:
    inbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
        - application: jamph-umami-frontend
          namespace: team-researchops
        - application: jamph-ml-trainer
          namespace: team-researchops
        - application: reops-felgen
          namespace: team-researchops
    outbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
  liveness:
    path: /health
    initialDelay: 20
  readiness:
    path: /health
    initialDelay: 5
  ingresses:
    - "https://jamph-rag-api-umami.ansatt.nav.no"
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "100m"
      memory: 512Mi
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 80
  env:
    - name: ENVIRONMENT
      value: "prod-gcp"
    - name: PORT
      value: "8004"
    - name: CORS_ALLOWED_ORIGIN
      value: "*.ansatt.nav.no"
    - name: OLLAMA_BASE_URL
      value: "http://jamph-ollama"
