apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jamph-rag-api-umami-dev
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
spec:
  image: "{{ image }}"
  port: 8004
  ttl: 3h
  envFrom:
    - secret: student-bigquery
  filesFrom:
    - secret: student-bigquery
      mountPath: /var/run/secrets/bigquery
  accessPolicy:
    inbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
        - application: jamph-umami-frontend-dev
          namespace: team-researchops
        - application: jamph-ml-trainer
          namespace: team-researchops
        - application: reops-felgen
          namespace: team-researchops
    outbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
      external:
        - host: bigquery.googleapis.com
        - host: www.googleapis.com
  liveness:
    path: /health
    initialDelay: 30
    timeout: 5
    periodSeconds: 15
    failureThreshold: 5
  readiness:
    path: /health
    initialDelay: 20
    timeout: 5
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - "https://jamph-rag-api-umami.ekstern.dev.nav.no"
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: "100m"
      memory: 256Mi
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 80
  env:
    - name: ENVIRONMENT
      value: "dev-gcp"
    - name: PORT
      value: "8004"
    - name: CORS_ALLOWED_ORIGIN
      value: "*.ansatt.dev.nav.no,*.ekstern.dev.nav.no"
    - name: OLLAMA_BASE_URL
      value: "http://jamph-ollama"