apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jamph-rag-api-umami-dev
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8004
  ttl: 3h
  accessPolicy:
    inbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
        - application: jamph-umami-frontend-dev
          namespace: team-researchops
        - application: jamph-ml-trainer
          namespace: team-researchops
        - application: reops-felgen
          namespace: team-researchops
    outbound:
      rules:
        - application: jamph-ollama
          namespace: team-researchops
  liveness:
    path: /health
    initialDelay: 20
  readiness:
    path: /health
    initialDelay: 5
  ingresses:
    - "https://jamph-rag-api-umami.ekstern.dev.nav.no"
#    - "https://jamph-rag-api-umami.ansatt.dev.nav.no"
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:
    - name: ENVIRONMENT
      value: "dev-gcp"
    - name: PORT
      value: "8004"
    - name: CORS_ALLOWED_ORIGIN
      value: "*.ansatt.dev.nav.no,*.ekstern.dev.nav.no"
    - name: OLLAMA_BASE_URL
      value: "http://jamph-ollama"